"""create players table

Revision ID: 4ab5bc9c79da
Revises: 
Create Date: 2026-07-02 11:30:50.202687

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '4ab5bc9c79da'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=80), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('warnings', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('skill_level', sa.Float(), nullable=True),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('is_setter', sa.Boolean(), nullable=False),
    sa.Column('position', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('whatsapp', name=op.f('u1_players_whatsapp'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    # ### end Alembic commands ###