"""create game registrations table

Revision ID: d545fcee814f
Revises: 49d804a86c37
Create Date: 2026-07-02 16:41:55.567114

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'd545fcee814f'
down_revision: str | None = '49d804a86c37'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_registrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('game_id', sa.String(length=40), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('slot', sa.String(length=20), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_registrations_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['players.id'], name=op.f('fk_game_registrations_invited_by_players'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_game_registrations_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_registrations')),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_game_registrations_game_id_player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_registrations')
    # ### end Alembic commands ###